### ISSUE TITLE
SPUserField not working with jQuery 1.9

### ISSUE THREAD

**Issue by rianchipman** [kitmenke/sputility#11]
SPUserField not working with jQuery 1.9 because of the line:
        this.SetValue = function (value) {
1518:            if ($.browser.msie) {

because jQuery seems to have deprecated this .msie line (see http://api.jquery.com/jquery.browser/)

Is there a version uses say:
		var isIE = ("ActiveXObject" in window)
See: http://stackoverflow.com/questions/17907445/how-to-detect-ie11

**Comment by kitmenke** [comment]
Fixed with the latest version (0.11.0) and tested with SharePoint 2007.
