### ISSUE TITLE
SPUtility.GetSPField return 50 instead of 50.000

### ISSUE THREAD

**Issue by uomoragno88** [kitmenke/sputility#22]
SPUtility.GetSPField return 50 instead of 50.000

Before:
Title		50.000  (fifty thousand in the European numbering system)

var myField = SPUtility.GetSPField('Title');
myField.MakeReadOnly();

After:
Title		50		(fifty)

I use SP2007

Can you fix the problem?
Thanks

Stefano

**Comment by kitmenke** [comment]
Stefano,
I'll take a look. Is this a Number field or a Currency field?

**Comment by uomoragno88** [comment]
Hi
Is a number field
Thanks
Il 14/mar/2016 04:33 PM, "Kit Menke" <notifications@github.com> ha scritto:

**Comment by kitmenke** [comment]
Awesome thanks. I found the issue inside convertStringToNumber. SPUtility.js is using javascript's parseFloat method which is not aware of locale (in this case, that period is not a decimal point but is thousands separator).

If this is urgent for you, you could take a look at modifying this line: https://github.com/kitmenke/sputility/blob/master/src/sputility.js#L55

I'll start working on a fix. I think I'll need to add some settings to change what character is used for decimal/thousands separators.

**Comment by uomoragno88** [comment]
I have fix line 55 with

val = match[0].replace(/\./g, '');

and the val returned is 50000 (not truncaded)

Another problem:

the numeric field lost original formatting after set to read only

Before:

50.000 (not read only)

After

50000 (read only without formatting)


Thanks

Questa e-mail è stata inviata da un computer privo di virus protetto da
Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-03-14 17:03 GMT+01:00 Kit Menke <notifications@github.com>:

> Awesome thanks. I found the issue inside convertStringToNumber.
> SPUtility.js is using javascript's parseFloat method which is not aware of
> locale (in this case, that period is not a decimal point but is thousands
> separator).
>
> If this is urgent for you, you could take a look at modifying this line:
> https://github.com/kitmenke/sputility/blob/master/src/sputility.js#L55
>
> I'll start working on a fix. I think I'll need to add some settings to
> change what character is used for decimal/thousands separators.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kitmenke/sputility/issues/22#issuecomment-196385665>.
>



-- 
stefano
http://stores.ebay.it/solo-memorie-e-cpu
uomoragno88 su ebay (PowerSeller)
Punteggio di feedback: 3480
Feedback positivi: 99,7%
Utente Ebay dal: 5 dicembre 2000
Email: uomoragno88@gmail.com
MSM Messenger: uomoragno88@gmail.com
Skype: uomoragno88

**Comment by ViktorHofer** [comment]
Hello. Fixed with my pull request :)

**Comment by kitmenke** [comment]
Thanks @ViktorHofer! I've merged the pull request. 

@uomoragno88, There are two new methods you can use to change the separators:
```
SPUtility.SetDecimalSeparator(',');
SPUtility.SetThousandsSeparator('.');
```
Just set these before the rest of your code and you should be all set!

**Comment by uomoragno88** [comment]
Hi,

all work fine
the only drawback is that when the numeric field is empty displays "NaN"

Thanks

uomoragno88

2016-03-23 2:09 GMT+01:00 Kit Menke <notifications@github.com>:

> Thanks @ViktorHofer <https://github.com/ViktorHofer>! I've merged the
> pull request.
>
> @uomoragno88 <https://github.com/uomoragno88>, There are two new methods
> you can use to change the separators:
>
> SPUtility.SetDecimalSeparator(',');
> SPUtility.SetThousandsSeparator('.');
>
> Just set these before the rest of your code and you should be all set!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/kitmenke/sputility/issues/22#issuecomment-200101016>
>



-- 
stefano
http://stores.ebay.it/solo-memorie-e-cpu
uomoragno88 su ebay (PowerSeller)
Punteggio di feedback: 3480
Feedback positivi: 99,7%
Utente Ebay dal: 5 dicembre 2000
Email: uomoragno88@gmail.com
MSM Messenger: uomoragno88@gmail.com
Skype: uomoragno88

**Comment by uomoragno88** [comment]
Hi,

all work fine
the only drawback is that when the numeric field is empty displays "NaN"

Thanks

2016-03-22 22:46 GMT+01:00 Viktor Hofer <notifications@github.com>:

> Hello. Fixed with my pull request :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kitmenke/sputility/issues/22#issuecomment-200044009>
>



-- 
stefano
http://stores.ebay.it/solo-memorie-e-cpu
uomoragno88 su ebay (PowerSeller)
Punteggio di feedback: 3480
Feedback positivi: 99,7%
Utente Ebay dal: 5 dicembre 2000
Email: uomoragno88@gmail.com
MSM Messenger: uomoragno88@gmail.com
Skype: uomoragno88

**Comment by kitmenke** [comment]
I'll open a new issue.
