### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by ViktorHofer** [kitmenke/sputility#24]
Hello,

just wondered, why isn't SPUtility available in bower? :facepunch: 

http://bower.io/search/?q=sputility

**Comment by kitmenke** [comment]
Only reason is I hadn't thought about it before!

I registered sputility but it isn't showing up in search yet.

**Comment by ViktorHofer** [comment]
Thanks, that's really great :)

**Comment by kitmenke** [comment]
Shows up in search! SPUtility.js, now with 100% more bower!
