### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by mchamera** [kitmenke/sputility#51]
I am trying to get SPutility to work in Sharepoint online. I could not get any scripts to work in neither script editor nor content editor web parts. I don't have access to custom forms advanced mode editing (yet - i hope i will get it soon from the admin). I managed to find a workaround by using Form HTML webpart and editing its source code and putting my script there. jQuery works and gives me the test alert, but nothing happens when i try to get an alert from SPUtility. ( I also tried using some functions on the form like autocomplete but no luck there as well. Here's the code:

````
<script language="javascript" type="text/javascript" src="/SiteAssets/jquery-3.2.1.js"></script>
<script language="javascript" type="text/javascript" src="/SiteAssets/jquery.SPServices.min.js"></script>
<script language="javascript" type="text/javascript">
$(document).ready(function() {
 alert("jQuery");
alert($().SPServices.SPGetCurrentSite());
});
</script>
````

**Comment by nvang1985** [comment]
Have you tried:
**var thisSite = $().SPServices.SPGetCurrentSite();
alert(thisSite);**

**Comment by kitmenke** [comment]
I think you've mixed up projects and meant to ask about [SPServices](https://github.com/sympmarc/SPServices)
